coke_can:
  foulder_path: '/home/gauss/projects/personal_ws/src/pybullet_utils/urdf'
  urdf_file_name: 'coke_can'

sphere:
  foulder_path: '/home/gauss/projects/personal_ws/src/pybullet_utils/urdf'
  urdf_file_name: 'sphere'
